name: Deploy to Server

on:
  push:
    branches:
      - main   # yoki master bo‘lsa o‘zgartirasan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/medme-b-test
            git pull origin main
            npm install --production
            pm2 restart all
